project:
  type: book
  output-dir: docs

highlight-style: "github"
code-block-bg: true
code-block-border-left: "#31BAE9"
code-line-numbers: true

book:
  title: "Data-Driven Decision-Making"
  author: "Judith Künneke, Harm Schütt"
  downloads: [docx]
  search: true
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - decision-making.qmd
    - datapatterns.qmd
    - diagnostics.qmd
    - predictions.qmd
    - reporting.qmd
    - case1.qmd
    - case4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: kable
  # pdf:
  #   documentclass: scrbook
  #   papersize: a4
  #   include-in-header:
  #     - text: |
  #         \usepackage{animate}
  docx:
    toc: true
    number-sections: true
