project:
  type: book
  output-dir: docs

book:
  title: "Data Driven Decision Making"
  author: "Judith Künneke, Harm Schütt"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - decision-making.qmd
    - datapatterns.qmd
    - predictions.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: kable
  pdf:
    documentclass: scrreprt



